unit-test:
  image: gradle:alpine
  stage: build
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apt add yt-dlp
  script:
    - gradle clean test --info

#build-and-push:
#  needs: [unit-test]
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  script:
#    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.mitchelltsutsulis.com
#    - docker build -t registry.mitchelltsutsulis.com/mitchellwt/tube_loader_server .
#    - docker push registry.mitchelltsutsulis.com/mitchellwt/tube_loader_server
