server:
  port: 8383

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password: password
    driverClassName: org.h2.Driver
  #datasource:
  #  url: jdbc:postgresql://localhost:5432/tube_loader
  #  username: username
  #  password: password
  #  driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

download:
  video-storage: "/opt/tube_loader/videos/"
  download-cron: "*/30 * * * * *"
  youtube-api-key: "API_KEY"
  downloader-config:
    - "--no-colors"
    - "--retries"
    - "infinite"
    - "--write-thumbnail"
    - "--format"
    - "mp4"

security:
  username: "username"
  password: "password"
  password-attempt-max: 5
